/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_include = 1,
  sym_include_target = 2,
  anon_sym_EQ = 3,
  sym_key = 4,
  anon_sym_COMMA = 5,
  sym_quoted_string = 6,
  aux_sym_bare_atom_token1 = 7,
  sym_comment = 8,
  sym_newline = 9,
  sym_source_file = 10,
  sym__line = 11,
  sym__statement = 12,
  sym_comment_line = 13,
  sym_include_statement = 14,
  sym_assignment = 15,
  sym_value = 16,
  sym_comma_list = 17,
  sym_atom_list = 18,
  sym_list_item = 19,
  sym_value_atom = 20,
  sym_bare_atom = 21,
  sym_bare_item = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_comma_list_repeat1 = 24,
  aux_sym_atom_list_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_include] = "include",
  [sym_include_target] = "include_target",
  [anon_sym_EQ] = "=",
  [sym_key] = "key",
  [anon_sym_COMMA] = ",",
  [sym_quoted_string] = "quoted_string",
  [aux_sym_bare_atom_token1] = "bare_atom_token1",
  [sym_comment] = "comment",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_comment_line] = "comment_line",
  [sym_include_statement] = "include_statement",
  [sym_assignment] = "assignment",
  [sym_value] = "value",
  [sym_comma_list] = "comma_list",
  [sym_atom_list] = "atom_list",
  [sym_list_item] = "list_item",
  [sym_value_atom] = "value_atom",
  [sym_bare_atom] = "bare_atom",
  [sym_bare_item] = "bare_item",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comma_list_repeat1] = "comma_list_repeat1",
  [aux_sym_atom_list_repeat1] = "atom_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_include] = anon_sym_include,
  [sym_include_target] = sym_include_target,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_key] = sym_key,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_quoted_string] = sym_quoted_string,
  [aux_sym_bare_atom_token1] = aux_sym_bare_atom_token1,
  [sym_comment] = sym_comment,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_comment_line] = sym_comment_line,
  [sym_include_statement] = sym_include_statement,
  [sym_assignment] = sym_assignment,
  [sym_value] = sym_value,
  [sym_comma_list] = sym_comma_list,
  [sym_atom_list] = sym_atom_list,
  [sym_list_item] = sym_list_item,
  [sym_value_atom] = sym_value_atom,
  [sym_bare_atom] = sym_bare_atom,
  [sym_bare_item] = sym_bare_item,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comma_list_repeat1] = aux_sym_comma_list_repeat1,
  [aux_sym_atom_list_repeat1] = aux_sym_atom_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [sym_include_target] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_bare_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_include_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_list] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_list] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_value_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_item] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_atom_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_item = 1,
  field_key = 2,
  field_target = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_item] = "item",
  [field_key] = "key",
  [field_target] = "target",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 1},
  [6] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_target, 1},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_item, 0},
    {field_item, 2},
  [5] =
    {field_item, 0},
    {field_item, 2},
    {field_item, 3, .inherited = true},
  [8] =
    {field_item, 1},
  [9] =
    {field_item, 0, .inherited = true},
    {field_item, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 12,
  [20] = 11,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 16,
  [25] = 25,
  [26] = 14,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(22);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_include);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_include_target);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(7);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'u') ADVANCE(11);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_quoted_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_bare_atom_token1);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ',') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_bare_atom_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ',') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_bare_atom_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ',') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym__line] = STATE(2),
    [sym__statement] = STATE(32),
    [sym_comment_line] = STATE(32),
    [sym_include_statement] = STATE(32),
    [sym_assignment] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      anon_sym_include,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_newline,
    STATE(3), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(30), 4,
      sym__statement,
      sym_comment_line,
      sym_include_statement,
      sym_assignment,
  [26] = 7,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(22), 1,
      sym_key,
    ACTIONS(25), 1,
      sym_comment,
    ACTIONS(28), 1,
      sym_newline,
    STATE(3), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(34), 4,
      sym__statement,
      sym_comment_line,
      sym_include_statement,
      sym_assignment,
  [52] = 8,
    ACTIONS(31), 1,
      sym_quoted_string,
    ACTIONS(33), 1,
      aux_sym_bare_atom_token1,
    STATE(22), 1,
      sym_bare_item,
    STATE(26), 1,
      sym_bare_atom,
    STATE(27), 1,
      sym_value,
    STATE(35), 1,
      sym_list_item,
    STATE(9), 2,
      sym_value_atom,
      aux_sym_atom_list_repeat1,
    STATE(28), 2,
      sym_comma_list,
      sym_atom_list,
  [79] = 8,
    ACTIONS(35), 1,
      sym_quoted_string,
    ACTIONS(37), 1,
      aux_sym_bare_atom_token1,
    STATE(14), 1,
      sym_bare_atom,
    STATE(22), 1,
      sym_bare_item,
    STATE(27), 1,
      sym_value,
    STATE(35), 1,
      sym_list_item,
    STATE(6), 2,
      sym_value_atom,
      aux_sym_atom_list_repeat1,
    STATE(28), 2,
      sym_comma_list,
      sym_atom_list,
  [106] = 5,
    ACTIONS(41), 1,
      sym_quoted_string,
    ACTIONS(43), 1,
      aux_sym_bare_atom_token1,
    STATE(14), 1,
      sym_bare_atom,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(7), 2,
      sym_value_atom,
      aux_sym_atom_list_repeat1,
  [124] = 5,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(50), 1,
      aux_sym_bare_atom_token1,
    STATE(14), 1,
      sym_bare_atom,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(7), 2,
      sym_value_atom,
      aux_sym_atom_list_repeat1,
  [142] = 5,
    ACTIONS(45), 1,
      sym_newline,
    ACTIONS(53), 1,
      sym_quoted_string,
    ACTIONS(56), 1,
      aux_sym_bare_atom_token1,
    STATE(26), 1,
      sym_bare_atom,
    STATE(8), 2,
      sym_value_atom,
      aux_sym_atom_list_repeat1,
  [159] = 5,
    ACTIONS(39), 1,
      sym_newline,
    ACTIONS(59), 1,
      sym_quoted_string,
    ACTIONS(61), 1,
      aux_sym_bare_atom_token1,
    STATE(26), 1,
      sym_bare_atom,
    STATE(8), 2,
      sym_value_atom,
      aux_sym_atom_list_repeat1,
  [176] = 2,
    ACTIONS(65), 2,
      anon_sym_include,
      sym_key,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
  [186] = 3,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(71), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [198] = 3,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(77), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [210] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_comma_list_repeat1,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_newline,
  [221] = 2,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(77), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [230] = 4,
    ACTIONS(83), 1,
      sym_quoted_string,
    ACTIONS(85), 1,
      aux_sym_bare_atom_token1,
    STATE(17), 1,
      sym_list_item,
    STATE(22), 1,
      sym_bare_item,
  [243] = 2,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(71), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [252] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_comma_list_repeat1,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_newline,
  [263] = 4,
    ACTIONS(83), 1,
      sym_quoted_string,
    ACTIONS(85), 1,
      aux_sym_bare_atom_token1,
    STATE(22), 1,
      sym_bare_item,
    STATE(25), 1,
      sym_list_item,
  [276] = 3,
    ACTIONS(73), 1,
      sym_newline,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(77), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [287] = 3,
    ACTIONS(67), 1,
      sym_newline,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    ACTIONS(71), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [298] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_comma_list_repeat1,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_newline,
  [309] = 1,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_newline,
  [315] = 1,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_newline,
  [321] = 2,
    ACTIONS(67), 1,
      sym_newline,
    ACTIONS(71), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [329] = 1,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_newline,
  [335] = 2,
    ACTIONS(73), 1,
      sym_newline,
    ACTIONS(77), 2,
      sym_quoted_string,
      aux_sym_bare_atom_token1,
  [343] = 1,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_newline,
  [348] = 1,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      sym_newline,
  [353] = 1,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_newline,
  [358] = 2,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      sym_newline,
  [365] = 1,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      sym_newline,
  [370] = 2,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      sym_newline,
  [377] = 1,
    ACTIONS(108), 1,
      sym_include_target,
  [381] = 1,
    ACTIONS(104), 1,
      sym_newline,
  [385] = 1,
    ACTIONS(110), 1,
      anon_sym_COMMA,
  [389] = 1,
    ACTIONS(112), 1,
      anon_sym_EQ,
  [393] = 1,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
  [397] = 1,
    ACTIONS(116), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 79,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 124,
  [SMALL_STATE(8)] = 142,
  [SMALL_STATE(9)] = 159,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 186,
  [SMALL_STATE(12)] = 198,
  [SMALL_STATE(13)] = 210,
  [SMALL_STATE(14)] = 221,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 243,
  [SMALL_STATE(17)] = 252,
  [SMALL_STATE(18)] = 263,
  [SMALL_STATE(19)] = 276,
  [SMALL_STATE(20)] = 287,
  [SMALL_STATE(21)] = 298,
  [SMALL_STATE(22)] = 309,
  [SMALL_STATE(23)] = 315,
  [SMALL_STATE(24)] = 321,
  [SMALL_STATE(25)] = 329,
  [SMALL_STATE(26)] = 335,
  [SMALL_STATE(27)] = 343,
  [SMALL_STATE(28)] = 348,
  [SMALL_STATE(29)] = 353,
  [SMALL_STATE(30)] = 358,
  [SMALL_STATE(31)] = 365,
  [SMALL_STATE(32)] = 370,
  [SMALL_STATE(33)] = 377,
  [SMALL_STATE(34)] = 381,
  [SMALL_STATE(35)] = 385,
  [SMALL_STATE(36)] = 389,
  [SMALL_STATE(37)] = 393,
  [SMALL_STATE(38)] = 397,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_list, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_atom_list_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_atom_list_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_atom_list_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_atom_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_atom_list_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_atom, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_item, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bare_atom, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_atom, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_atom, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_list, 4, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_list, 3, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_list_repeat1, 2, 0, 6),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_list_repeat1, 2, 0, 6), SHIFT_REPEAT(18),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_list_repeat1, 2, 0, 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 2, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [114] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_taskwarrior(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "taskwarrior",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
